name: PR Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  issue_comment:

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      contents: write
      checks: write

    name: Run PR Agent

    steps:
      - name: PR Agent
        id: pragent
        uses: the-pr-agent/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          config.model: "groq/openai/gpt-oss-120b"
          config.fallback_models: '["groq/openai/gpt-oss-20b"]'

          GROQ__KEY: ${{ secrets.GROQ_API_KEY }}

          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
